server.port=8082

# ── Base 1 : bh_guard_db ───────────────────────────
spring.datasource.jdbcUrl=jdbc:sqlserver://LAPTOP-08TRQOEP\\SQLEXPRESS;databaseName=bh_guard_db;integratedSecurity=true;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.auto-commit=true
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

# Fix connexion fermée
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.max-lifetime=120000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=3000

# ── Base 2 : bh_assurance ──────────────────────────
sinistres.datasource.jdbcUrl=jdbc:sqlserver://LAPTOP-08TRQOEP\\SQLEXPRESS;databaseName=bh_assurance;integratedSecurity=true;encrypt=true;trustServerCertificate=true
sinistres.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ── JPA ────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ── FastAPI ────────────────────────────────────────
fastapi.url=http://localhost:8000

# ── Mail ───────────────────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ghalia.hazem.2023@ihec.ucar.tn
spring.mail.password=cpgqdactjykwqrkm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true